### ISSUE TITLE
GET /api/charts returned a 500

### ISSUE THREAD

**Issue by algodave** [rubyforgood/Flaredown#65]
Reported by @squiggie 
Can you paste the request body here? Thanks

**Comment by squiggie** [comment]
http://staging.flaredown.com/api/charts?end_at=2016-05-04&id=health&start_at=2016-03-20

vendor-54a080e….js:12 Error: Ember Data Request GET /api/charts returned a 500
Payload (application/json; charset=utf-8)
[object Object]
    at new Error (native)
    at Error.r (http://staging.flaredown.com/assets/vendor-54a080ecf13de66b1a5b0c29e486c4be.js:8:16181)
    at Error.n (http://staging.flaredown.com/assets/vendor-54a080ecf13de66b1a5b0c29e486c4be.js:28:15227)
    at e.default.r.default.extend.handleResponse (http://staging.flaredown.com/assets/vendor-54a080ecf13de66b1a5b0c29e486c4be.js:31:18121)
    at o.extend.handleResponse (http://staging.flaredown.com/assets/vendor-54a080ecf13de66b1a5b0c29e486c4be.js:27:19787)
    at r [as handleResponse](http://staging.flaredown.com/assets/vendor-54a080ecf13de66b1a5b0c29e486c4be.js:10:1949)
    at e.default.t.default.Mixin.create.handleResponse (http://staging.flaredown.com/assets/vendor-54a080ecf13de66b1a5b0c29e486c4be.js:33:16919)
    at r [as handleResponse](http://staging.flaredown.com/assets/vendor-54a080ecf13de66b1a5b0c29e486c4be.js:10:1949)
    at c.error (http://staging.flaredown.com/assets/vendor-54a080ecf13de66b1a5b0c29e486c4be.js:31:18690)
    at l (http://staging.flaredown.com/assets/vendor-54a080ecf13de66b1a5b0c29e486c4be.js:2:10310)

**Comment by algodave** [comment]
this is related to:
https://flaredown.airbrake.io/projects/121837/groups/1665088222926919501/notices/1665088223526050787

**Comment by algodave** [comment]
The following is failing anyways on staging:

`Checkin.where(user_id: id)`

because there's no Checkin collection currently

**Comment by safeforge** [comment]
@algodave my fault,  `MONGOLAB_URI` was **nil**
